// <auto-generated />
using System;
using LoanMe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanMe.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204134106_Add_InterestFreeMonths_Column_In_Product_Entity")]
    partial class Add_InterestFreeMonths_Column_In_Product_Entity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanMe.Data.Entities.DraftLoan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("bit");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("Term")
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DraftLoans");
                });

            modelBuilder.Entity("LoanMe.Data.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("EstablishmentFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short?>("InterestFreeMonths")
                        .HasColumnType("smallint");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanAmountMaximum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanAmountMinimum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("LoanTermMaximum")
                        .HasColumnType("smallint");

                    b.Property<short>("LoanTermMinimum")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "This product is interest-free loan.",
                            EstablishmentFee = 300m,
                            InterestRate = 0m,
                            LoanAmountMaximum = 2000000m,
                            LoanAmountMinimum = 10000m,
                            LoanTermMaximum = (short)300,
                            LoanTermMinimum = (short)1,
                            Name = "House"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "This product gives the first 2 months interest-free but the loan term duration is 6 months minimum.",
                            EstablishmentFee = 250m,
                            InterestFreeMonths = (short)2,
                            InterestRate = 0.05m,
                            LoanAmountMaximum = 20000m,
                            LoanAmountMinimum = 1000m,
                            LoanTermMaximum = (short)60,
                            LoanTermMinimum = (short)6,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "This product provides no interest-free.",
                            EstablishmentFee = 100m,
                            InterestFreeMonths = (short)0,
                            InterestRate = 0.02m,
                            LoanAmountMaximum = 2000m,
                            LoanAmountMinimum = 100m,
                            LoanTermMaximum = (short)3,
                            LoanTermMinimum = (short)1,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("LoanMe.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DateOfBirth");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoanMe.Data.Entities.DraftLoan", b =>
                {
                    b.HasOne("LoanMe.Data.Entities.User", "User")
                        .WithOne("DraftLoan")
                        .HasForeignKey("LoanMe.Data.Entities.DraftLoan", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoanMe.Data.Entities.User", b =>
                {
                    b.Navigation("DraftLoan");
                });
#pragma warning restore 612, 618
        }
    }
}
